config/routes.rb
Rails.application.routes.draw do

  get 'yelps/index'

  root 'pages#home'
  get 'users/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pages/about'
  get '/selected/random_item'
  get '/selected/random_restaurant'



  get '/restaurants/:id/random_menu' => 'restaurants#random_menu'

  resources :users do
    resources :restaurants
  end

  resources :restaurants do
    resources :menus, only: [ :index, :new, :create]
  end
  resources :menus, only: [ :show, :edit, :update, :destroy]

  resources :menus do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [ :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/selected_controller.rb
class SelectedController < ApplicationController

  def random_item

    @user = current_user
    @restaurants = @user.restaurants
    @menus = Restaurant.where(user_id: @user.id)
    # Begin ### Block defines @user_items
    item_arr = []
    @restaurants.each do |restaurant|
      restaurant.menus.each do |menu|
        menu.items.each do |item|
          item_arr << item
           item_arr.flatten!
        end
      end
    end
    @user_items = []
    randomized_arr = []
    item_arr.shuffle.each do |item|
      @user_items << item
      randomized_arr << item[:item_name]
      randomized_arr.flatten!
    end
    # End ### Block defines  @user_items

    @items = @user_items
    @menu = @user_items[0].menu
    @item = @user_items[0]


  end


  def random_restaurant
    @user = current_user
    @restaurants = Restaurant.where(user_id: current_user ).paginate(page: params[:page]).order("created_at DESC")
    @selected_restaurant = @restaurants.shuffle.first
  end

end

app/helpers/selected_helper.rb
module SelectedHelper
end

app/views/selected/random_item.html.erb
<p id="notice"><%= notice %></p>

<% if 1 >= @items.count  %>

  <div class="card text-center py-5">
    <h5>
      <font color="red">
        <%= link_to 'You Need to Add At Least 2 Items to Generate a Random Item.', new_user_item_path(@user), :style => "color: #f40404;" %>
        </font>
    </h5>
  </div>

<% else %>

<br>
<br>

<div class="float-right">

  <%= link_to "My Profile", user_path(@user), :style=>'color:#291f41;' %>
  >
  <%= link_to "#{@item.menu.restaurant.title.capitalize}", user_path(@user), :style=>'color:#291f41;' %>
  >
  <%= link_to "#{@item.menu.title.capitalize} Menu", user_path(@user), :style=>'color:#291f41;' %>
  >
    <strong>
    <u>
      <%= link_to "Random Item", selected_random_item_path, :style=>'color:#291f41;' %>
    </u>
    </strong>
</div>
<br>


<div class="card">
  <div class="container">
    <br>
    <br>
    <h1 class="display-4"> Random Item </h1>
    <br>
    <br>
  </div>
</div>

<br>
<br>
    <br>
    <div class="card">
      <div class="card-header text-center ">
        <h2>
        You Got
        </h2>
      </div>

      <div class="card-body text-center">
        <h2 class="card-title display-4">
          <%= link_to "#{@item.item_name}", item_path(@item), :style=>'color:#291f41;' %>
        </h2>

        <%= link_to 'Generate Random Item', selected_random_item_path, class:"btn btn-info btn-lg btn-block" %>

      </div>
      <br>
      <div class="card-footer text-muted text-center">
          Added <%= time_ago_in_words(@item.created_at) %> ago.
      </div>
    </div>

  <br>
  <br>

<% end %>
<br>

<%= link_to 'Back', root_path, class:"btn btn-primary", :style => "color: #f8f8f8;"  %>

app/views/selected/random_restaurant.html.erb
<p id="notice"><%= notice %></p>

<% if 1 >= @restaurants.count  %>

  <div class="card text-center py-5">
    <h5>
      <font color="red">
        <%= link_to 'You Need to Add At Least 2 Restaurants to Generate a Random Restaurant.', new_user_restaurant_path(@user), :style => "color: #f40404;" %>
        </font>
    </h5>
  </div>

<% else %>

<br>
<br>

<div class="float-right">

    <%= link_to "My Profile", user_path(@user), :style=>'color:#291f41;' %>
    >
    <strong>
    <u>
      <%= link_to "Random Restaurant", selected_random_restaurant_path, :style=>'color:#291f41;' %>
    </u>
    </strong>
</div>
<br>


<div class="card">
  <div class="container">
    <br>
    <br>
    <h1 class="display-4"> Random Restaurant </h1>
    <br>
    <br>
  </div>
</div>

<br>
<br>
    <br>
    <div class="card">
      <div class="card-header text-center ">
        <h2>
        You Got
        </h2>
      </div>

      <div class="card-body text-center">
        <h2 class="card-title display-4">
          <%= link_to "#{@selected_restaurant.title}", restaurant_path(@selected_restaurant), :style=>'color:#291f41;' %>
        </h2>

        <%= link_to 'Generate Random Restaurant', selected_random_restaurant_path, class:"btn btn-info btn-lg btn-block" %>

      </div>
      <br>
      <div class="card-footer text-muted text-center">
          Added <%= time_ago_in_words(@selected_restaurant.created_at) %> ago.
      </div>
    </div>



  <br>
  <br>

<% end %>
<br>

<%= link_to 'Back', root_path, class:"btn btn-primary", :style => "color: #f8f8f8;"  %>