config/routes.rb
Rails.application.routes.draw do

  get 'yelps/index'

  root 'pages#home'
  get 'users/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pages/about'
  get '/selected/random_item'
  get '/selected/random_restaurant'



  get '/restaurants/:id/random_menu' => 'restaurants#random_menu'

  resources :users do
    resources :restaurants
  end

  resources :restaurants do
    resources :menus, only: [ :index, :new, :create]
  end
  resources :menus, only: [ :show, :edit, :update, :destroy]

  resources :menus do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [ :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

  has_many :restaurants, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
    # @restaurants = Restaurant.where(user_id: @user).paginate(page: params[:page]).order("created_at DESC")
    #### Pagination found in model.rb file(control amount of @instances per page)
  end

  def show
    @user = current_user
    @user_restaurants = @user.restaurants.order("created_at DESC")
    @restaurant = @user.restaurants.build
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create

    # user = User.new(user_params)
    @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to current_user

        flash[:register_success] = ["Welcome #{current_user.email}, thank you for registering."]
      else
        flash[:register_errors] = ["REGISTER ERROR. Invalid credentials, please try again."]
        # redirect_to users_index_path
        redirect_to root_path
      end
  end

  def update

      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to @user, :notice => "Profile updated successfully."
      else
         redirect_to @user, :notice => ['Profile could not be updated, please try again later.']
      end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => 'You have deleted your profile.'
   else
     redirect_to users_edit_path, :notice => ["User can not be deleted at this time."]
   end
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit( :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <br>
    <%= form.text_field :email, id: :user_email%>
  </div>
<br>

  <div class="field">
    <%= form.label :password %>
    <br>
    <%= form.password_field :password, id: :user_password %>
  </div>
<br>

  <div class="field">
    <%= form.label :password, "Password Confirmation" %>
    <br>
    <%= form.password_field :password_confirmation, id: :user_password %>
  </div>
<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

  <td><%= link_to 'Deactivate Account', {:controller=>:users,:action=>:destroy, :id=>@user}, :method=>:delete, data: { confirm: 'Are you sure you would like to deactivate your account forever? Once deactivated it can never be recovered.' }, class:"btn btn-sm btn-danger", :style => "color: #f8f8f8;" %></td>

  <hr>
  <br>
  

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

<h1> Welcome <%= @user.email %></h1>


<% @restaurants.each do |restaurant| %>

  <%= restaurant.title %>

<% end %>

app/views/users/edit.html.erb
<div class="card py-5 text-center">
<div class="container">


<h1 class="text-center">Account Settings</h1>
<hr>
<%= render 'form', user: @user %>

<div>
  <%= link_to 'Back', :back, class:"btn btn-outline-primary" %>
</div>


</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user| %>
 <%= user.email %>
<% end %>

app/views/users/new.html.erb
<div class="card">
  <br>

  <h1 class="text-center">Signup</h1>

  <div class="container">
    <hr>
  </div>


<br>

  <%= form_for :user, url: '/users' do |f| %>

      <div class="form-group">
      <strong>Email:</strong>  <%= f.text_field :email, placeholder: "Enter your Email" %>
      </div>

      <div class="form-group">
        <strong>Password:</strong><%= f.password_field :password, placeholder: "Password" %>
      </div>

      <div class="form-group">
            <strong>Confirm Password:</strong>  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
      </div>

      <br>
       <center class="submit">
        <%= f.submit "Submit", class:"btn btn-success" %>
      </center>
      <br>

      <small>
        Already have an account? <%= link_to "Click Here to Login.", login_path %>
      </small>

      <br>
  <% end %>

<br>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<br>
<br>
<br>

<div class="card">
  <div class="container">
    <br>
    <br>
    <h1 class="display-4">  Welcome <%= current_user.email %> </h1>
    <br>
    <br>
  </div>
</div>

<br>
<br>
<br>

<div class="card">
  <div class="card-body">

    <% if @user_restaurants.count != nil %>
        <br>
        <h2>Restaurants</h2>

        <h4> You have <%= @user_restaurants.count %> Restaurants. </h4>


          <hr>
          <div class="container text-center">

            <%= link_to 'Generate Random Restaurant', selected_random_restaurant_path, class:"btn btn-info btn-lg" %>

            <!-- <%= link_to 'Generate Random Item', selected_random_item_path, class:"btn btn-outline-info btn-lg" %> -->

          </div>

        <hr>

        <br>

          <%= link_to 'Add Restaurant', new_user_restaurant_path(@user), class:"btn btn-success btn-block btn-lg", :style => "color: #f8f8f8;" %>

        <br>

          <div class="conatiner">
          <% @user_restaurants.each do |restaurant| %>

            <br>

            <div class="card">
              <div class="card-body">

                <h5 class="card-title">
                   <%= restaurant.title.capitalize %>
                </h5>


                <%= link_to 'View Restaurant', restaurant_path(restaurant), class:"btn btn-primary", :style => "color: #f8f8f8;" %>



                <!-- Would be rad to put view menus here to lessen confusion -->
                <!-- Would be rad to put view menus here to lessen confusion -->
                <!-- Would be rad to put view menus here to lessen confusion -->

                <!-- Button trigger modal -->
                <!-- <div>
                  <button type="button" class="btn  btn-success" data-toggle="modal" data-target="#exampleModal">
                    More Details
                  </button> -->

                  <!-- Modal -->
                  <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">


hello

                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div> -->
                <!-- Would be rad to put view menus here to lessen confusion -->

                <!-- ending modal brah -->
                <!-- ending modal brah -->
                <!-- ending modal brah -->
                <!-- ending modal brah -->


              </div>  <!-- card body div end -->

              <div class="card-footer text-muted text-center small">
                  Added <%= time_ago_in_words(restaurant.created_at) %> ago.
              </div>
            </div>

              <% end %>
          </div>   <!-- end of container div right above loop -->

        </div>


    <% else %>

      <%= link_to "View All Restaurants",  user_restaurants_path(@user), class:"btn btn-primary btn-block"  %>

      <br>

      <%= link_to 'Generate Random Restaurant', selected_random_restaurant_path, class:"btn btn-outline-primary" %>

    <% end %>

    <br>

  </div>
</div>