config/routes.rb
Rails.application.routes.draw do

  get 'yelps/index'

  root 'pages#home'
  get 'users/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pages/about'
  get '/selected/random_item'
  get '/selected/random_restaurant'



  get '/restaurants/:id/random_menu' => 'restaurants#random_menu'

  resources :users do
    resources :restaurants
  end

  resources :restaurants do
    resources :menus, only: [ :index, :new, :create]
  end
  resources :menus, only: [ :show, :edit, :update, :destroy]

  resources :menus do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [ :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  # validates :name, :presence => true

  belongs_to :user
  has_many :menus, dependent: :destroy

  self.per_page = 3
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy]

  def random_menu
    @user = current_user
  end


  def index
    @user = current_user
    @user.restaurants
    # @restaurants = Restaurant.where(user_id: current_user ).paginate(page: params[:page]).order("created_at DESC")
    #### Pagination found in model.rb file(control amount of @instances per page)
  end

  def show
    @user = current_user
    @restaurant = Restaurant.find(params[:id])
    @menus = Menu.where(restaurant_id: @restaurant ).paginate(page: params[:page]).order("created_at DESC")

    @restaurants = @user.restaurants
    # @items
  end

  def new
    @user = current_user
    @restaurant = @user.restaurants.build
  end

  def edit
    @user = current_user
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.build(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to user_restaurant_path(@user, @restaurant), notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = current_user
    # @menus = Menu.where(restaurant_id: @restaurant ).paginate(page: params[:page]).order("created_at DESC")
    @menus = @restaurant.menus

    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:title, :user_id)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: @restaurant, local: true) do |form| %>
<%#= form_with(model: [ @user, @user.restaurants.build ]) do |form| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this @restaurant from being saved:</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card text-center py-5">
  <div class="field">
      <%= form.hidden_field :user_id, id: :user_id, value: @user.id %>
  </div>

  <!-- <div>
    <%= "User ID" %>
    <br>
    <%= current_user.id %>
    <br>
    <% form.label :user_id %>
    <% form.text_area :user_id, id: :current_user_id %>
  </div> -->

  <div class="field">
    <strong> <%= form.label :title %>: </strong>
    <%= form.text_field :title, id: :restaurant_title, :required => true  %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit  class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/restaurants/_rendered.html.erb
<p id="notice"><%= notice %></p>

<div class="card py-5 text-center">

  <h1>Restaurants</h1>

  <br>

  <div class="container">

      <%= link_to 'Generate Random Restaurant', selected_random_restaurant_path, class:"btn btn-outline-primary" %>
  <hr>

  <div class="container">
    <%= link_to 'New Restaurant', new_restaurant_path(@user), class:"btn btn-success btn-block", :style => "color: #f8f8f8;" %>
  </div>

  <br>

    <div class="conatiner">
    <% @restaurants.each do |restaurant| %>
      <div class="card">

        <br>
        <div class="card-body text-center">
          <h5 class="card-title"> <%= restaurant.title %> </h5>
          <h6 class="card-title"> User's ID who posted restaurant: <%= restaurant.user_id %> </h6>

          <%#= link_to 'Show', user_restaurant_path(@user, restaurant ), class:"btn btn-primary", :style => "color: #f8f8f8;"  %>

          <%= link_to 'Show', restaurant_path(@user), class:"btn btn-primary", :style => "color: #f8f8f8;"  %>


        </div>
        <div class="card-footer text-muted text-center">
            Added <%= time_ago_in_words(restaurant.created_at) %> ago.
        </div>

        <% end %>
      </div>
    </div>
  <hr>
  <br>

  <div class="text-center">
    <%= will_paginate @restaurants, page_links: false %>
  </div>

  <hr>


  <br>
  <div>
  <%= link_to 'Back', :back, class:"btn btn-primary", :style => "color: #f8f8f8;"  %>
  </div>

</div>

app/views/restaurants/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <br>
  <div class="container">
    <br>
    <h1 class="display-4"> Edit <%= @restaurant.title.capitalize %> </h1>
    <br>
    <br>
  </div>
</div>
<br>
<br>
<%= render 'form', restaurant: @restaurant %>
<br>
<hr>
<br>
<div>
  <%= link_to 'Back', :back, class:"btn btn-primary", :style => "color: #f8f8f8;" %>
</div>

app/views/restaurants/index.html.erb
<h1> Restaurants#Index</h1>


<% @restaurants.each do |restaurant| %>
<% restaurant.title %>
<% end %>

app/views/restaurants/new.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="card">
  <br>
  <div class="container">
    <br>
    <h1 class="display-4"> New Restaurant </h1>
    <br>
    <br>
  </div>
</div>

<br>

<br>
<%= render 'form', restaurant: @restaurant %>

<br>

<hr>

<br>

<div>
  <%= link_to 'Back', :back, class:"btn btn-primary", :style => "color: #f8f8f8;" %>
</div>

app/views/restaurants/random_menu.html.erb
<h1> Random Menu</h1>

app/views/restaurants/show.html.erb
<div class="text-center">
<p id="notice"><%= notice %></p>


<!-- <% @menus.each do |menu| %>
<%= menu.items %>
<br>
<% end %> -->


<br>
<br>
<div class="float-right">
    <%= link_to "My Profile",  user_path(@user), :style=>'color:#291f41;' %>
    >
    <strong>
    <u>
      <%= link_to "#{@restaurant.title.capitalize}", restaurant_path(@restaurant), :style=>'color:#291f41;' %>
    </u>
    </strong>
</div>

<br>


<div class="card">
  <br>
  <div class="container">
    <br>
    <h4><strong>Restaurant: </strong> </h4><h1 class="display-4"> <%= "#{@restaurant.title.capitalize}"%></h1>
    <br>

    <%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant), class:"btn btn-outline-secondary btn-sm" %>

    <%= link_to 'Delete Restaurant', restaurant_path(@restaurant) , method: :delete, data: { confirm: 'Are you sure you would like to delete this restaurant forever?' }, class:"btn btn-danger btn-sm", :style => "color: #f8f8f8;"  %>

    <br>
    <br>
    <br>
  </div>
</div>


<br>
<br>
<br>

  <div class="card container">

    <br>
    <br>
    <h2> Menus</h2>
    <h4> <%= "#{@restaurant.title.capitalize}"%> has <%= @menus.count %> menus.
    </h4>


    <!-- <hr>
    <div>
      <%= link_to 'Generate Random Item', selected_random_restaurant_path, class:"btn btn-outline-primary" %>
    </div>
    <hr> -->


    <!--  -->
    <!--  -->
    <!--  -->

<hr>
    <!-- <div class="container text-center">

      <%= link_to 'Generate Random Menu', '#', class:"btn btn-outline-info btn-lg" %>
    </div>
    <hr> -->
    <!--  -->
    <!--  -->
    <!--  -->

      <%= link_to "Add Menu", new_restaurant_menu_path(@restaurant), class:"btn btn-block btn-success btn-lg", :style => "color: #f8f8f8;"  %>

    <div class="conatiner">
    <% @menus.each do |menu| %>

    <br>

      <div class="card">

        <div class="card-body">
          <h5 class="card-title">
            <%= menu.title.capitalize %> Menu
          </h5>

          <%= link_to 'View Menu', menu_path(menu), class:"btn btn-primary", :style => "color: #f8f8f8;" %>

        </div>

        <div class="card-footer text-muted text-center small">
            Added <%= time_ago_in_words(menu.created_at) %> ago.
        </div>
      </div>
    <% end %>

    </div>

    <hr>
    <br>

    <div class="text-center">
      <%= will_paginate @menus, page_links: false %>
      <!-- <%= will_paginate(@menus) %> -->
    </div>

    <div>
      <%= link_to 'Back', user_path(@user), class:"btn btn-primary", :style => "color: #f8f8f8;"  %>
    </div>

    <br>

  </div>
</div>


</div>