config/routes.rb
Rails.application.routes.draw do

  get 'yelps/index'

  root 'pages#home'
  get 'users/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/pages/about'
  get '/selected/random_item'
  get '/selected/random_restaurant'



  get '/restaurants/:id/random_menu' => 'restaurants#random_menu'

  resources :users do
    resources :restaurants
  end

  resources :restaurants do
    resources :menus, only: [ :index, :new, :create]
  end
  resources :menus, only: [ :show, :edit, :update, :destroy]

  resources :menus do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [ :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :menu

  self.per_page = 3
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :random_item]
  before_action :set_user


  def random_item
    @user = current_user

    @items = Item.where(menu_id: Menu.find(params[:menu_id])).paginate(page: params[:page]).order("created_at DESC")
    @selected_item = @items.all.shuffle.first
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(page: params[:page]).order("created_at DESC")
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @menu = @item.menu
  end

  # GET /items/new
  def new
    # @item = Item.new
    @menu = Menu.find(params[:menu_id])
    @item = @menu.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    # @item = Item.new(item_params)
    @menu = Menu.find(params[:menu_id])
    @item = @menu.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy

    @user = current_user
    @menu = @item.menu


    @item.destroy
    respond_to do |format|
      format.html { redirect_to menu_path(@menu), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_name, :price, :description, :menu_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [ @menu, @menu.items.build ]) do |form| %>

<%#= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="card text-center py-5">
    <div class="field">
      <strong> <%= form.label :item_name %>: </strong>
      <%= form.text_field :item_name, id: :item_item_name, :required => true   %>
    </div>
    <hr>

    <div class="field">
    <strong>  <%= form.label :price %>: </strong>
      <%= form.text_field :price, id: :item_price %>
    </div>
    <hr>

    <div class="field">
    <strong>  <%= form.label :description %>: </strong>
      <%= form.text_area :description, id: :item_description %>
    </div>
    <hr>
    <br>

    <div class="actions">
      <%= form.submit  class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1 class="text-center">Editing Item</h1>
<br>
<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="card text-center py-5">
    <div class="field">
      <%= form.label :item_name %>
      <%= form.text_field :item_name, id: :item_item_name %>
    </div>
    <hr>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :item_price %>
    </div>
    <hr>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :item_description %>
    </div>
    <hr>
    <br>

    <div class="actions">
      <%= form.submit  class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

<div class="text-center py-5">
  <%= link_to 'Back', :back, class:"btn btn-primary", :style => "color: #f8f8f8;"  %>

</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card py-5 text-center">

  <h1>Menu Items</h1>
  <br>

  <div class="container">

    <% if @items.count == 0 %>
    <div class="card text-center py-5">
      <a href="/items/new">
          <h5> Please Add At Least 2 Items So We Can Generate a Random Item. </h5>
      </a>
    </div>
  <% elsif @items.count <= 1  %>
    <div class="card text-center py-5">
      <a href="/items/new">
          <h5> Please Add At Least 1 More Item So We Can Generate a Random Item. </h5>
      </a>
    </div>
    <% else @items.count > 2 %>
      <%= link_to 'Generate Random Item', selected_random_item_path, class:"btn btn-outline-primary" %>
  <% end %>

  <hr>

  <div class="container">
    <%= link_to 'New Item', new_menu_item_path, class:"btn btn-success btn-block", :style => "color: #f8f8f8;" %>
  </div>

  <br>

    <div class="conatiner">
    <% @items.each do |item| %>
      <div class="card">

        <br>
        <div class="card-body text-center">
          <h5 class="card-title"> <%= item.item_name %> </h5>
          <p class="card-text"> <%= item.description %></p>
          <p class="card-text"> $<%= item.price %></p>
          <%= link_to 'Show', item_path(item), class:"btn btn-primary", :style => "color: #f8f8f8;"  %>
        </div>
        <div class="card-footer text-muted text-center">
            Added <%= time_ago_in_words(item.created_at) %> ago.
        </div>

        <% end %>
      </div>
    </div>
  <hr>
  <br>

  <div class="text-center">
    <%= will_paginate(@items) %>
    <!-- <%= will_paginate @items, page_links: false %> -->
  </div>

  <hr>


  <br>
  <div class="">
  <%= link_to 'Back', :back, class:"btn btn-primary", :style => "color: #f8f8f8;"  %>
  </div>

</div>

app/views/items/new.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <br>
  <div class="container">
    <br>
    <h1 class="display-4"> New Item </h1>
    <br>
    <br>
  </div>
</div>
<br>

<br>
<%= render 'form', item: @item %>

<br>
<hr>
<br>


<div>
  <%= link_to 'Back', menu_path(@menu), class:"btn btn-primary", :style => "color: #f8f8f8;" %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<div class="float-right">

    <%= link_to "My Profile",  user_path(@user), :style=>'color:#291f41;' %>
    >
    <%= link_to "#{@item.menu.restaurant.title.capitalize}", restaurant_path(@menu.restaurant.id), :style=>'color:#291f41;' %>
    >
    <%= link_to "#{@item.menu.title.capitalize} Menu", menu_path(@menu), :style=>'color:#291f41;' %>
    >
    <strong>
    <u>
        <%= link_to " #{@item.item_name.capitalize}", menu_path(@menu), :style=>'color:#291f41;' %>
    </u>
    </strong>
</div>

<br>

<div class="card">
  <br>
  <div class="container">
  <br>

  <h4><strong> Item: </strong> </h4>

  <h1 class="display-4"> <%= "#{@item.item_name.capitalize}"%> </h1>
  <%= link_to 'Edit Item', edit_item_path(@item), class:"btn btn-outline-secondary btn-sm" %>

  <%= link_to 'Delete Item', @item , method: :delete, data: { confirm: 'Are you sure you would like to delete this item forever?' }, class:"btn btn-danger btn-sm", :style => "color: #f8f8f8;"  %>

  <br>
  <br>
  <br>
  </div>
</div>

<br>



<hr>

<div class="text-center">
<%= link_to 'Back', menu_path(@menu), class:"btn btn-primary", :style => "color: #f8f8f8;"  %>
</div>